# 首页配置
index:
  slogan:
    enable: true
    text: '学习与生活记录'
  banner_img: /images/banner.jpg
  banner_img_height: 100
  banner_mask_alpha: 0.3

# 导航栏
navbar:
  blog_title: "Roger's Blog"
  menu:
    - { key: 'home', link: '/', icon: 'iconfont icon-home-fill' }
    - { key: 'archive', link: '/archives/', icon: 'iconfont icon-archive-fill' }
    - { key: 'category', link: '/categories/', icon: 'iconfont icon-category-fill' }
    - { key: 'tag', link: '/tags/', icon: 'iconfont icon-tags-fill' }
    - { key: 'about', link: '/about/', icon: 'iconfont icon-user-fill' }

# 文章页
post:
  meta:
    author:
      enable: true
    date:
      enable: true
    category:
      enable: true
  toc:
    enable: true
    headingSelector: "h1,h2,h3,h4,h5,h6"
    collapseDepth: 0

# 侧边栏
sidebar:
  enable: true
  widgets:
    - {type: profile}
    - {type: category}
    - {type: tag}
    - {type: recent_posts}
    - {type: archive}

# 页脚
footer:
  content: '
    <a href="https://hexo.io" target="_blank" rel="nofollow noopener">
      <span>Powered by Hexo</span>
    </a>
    <br/>
    <a href="https://github.com/fluid-dev/hexo-theme-fluid" target="_blank" rel="nofollow noopener">
      <span>Theme Fluid</span>
    </a>
  '

# Gitalk 评论系统
comments:
  enable: true
  type: gitalk
  gitalk:
    clientID: 'Ov23li3O6mSTFDnQCLoM'    # 从 GitHub Application 获取
    clientSecret: '1434bf55dd5477845e6c15385d3485d3f88614d4'  # 从 GitHub Application 获取
    repo: 'blog-comments'    # 存储评论的仓库
    owner: 'itouchgod'   # 仓库所有者
    admin: ['itouchgod']  # 仓库管理员
    language: zh-CN    # 语言设置
    labels: ['Gitalk'] # 标签
    perPage: 10       # 每页评论数
    distractionFreeMode: false  # 专注模式